In [3]:
import pandas as pd
import numpy as np
import os

In [ ]:
ethn_df = pd.read_csv("../Data/id_gender_ethnicity.tsv", sep='\t', header=None, names=['id', 'gender', 'ethnicity'])
ethn_df

                   id  gender  ethnicity
0          3211298559       1     french
1         82733984485       1     french
2         99029428429       0      czech
3         71174220620       1    swedish
4         47408331317       1     french
5         98636287555       2     danish
6         26492431555       0     french
7         15555134646       2     indian
8         87003659100       0     indian
9         85036593491       0     jewish
10        32650965483       1     french
11         1182893130       0     indian
12        96399498229       1     indian
13        47419260818       0    russian
14        34543928980       2     french
15        64100723165       2     jewish
16         9722298659       1     jewish
17        15440362028       0     jewish
18        64531383178       2    spanish
19        13650827896       2    spanish
20        17071017327       2    russian
21        70345004147       2    spanish
22        47700091792       2     french
23        22701256151       2     french
24        90734518496       0    spanish
25        96700384433       0     french
26        43133826290       1    spanish
27        33192307085       0      irish
28        61542611583       1     french
29        42448628669       0      swiss
...               ...     ...        ...
32282743  27815203475       2      swiss
32282744  45139910026       2     jewish
32282745  87996340829       2     french
32282746  74351154675       2     french
32282747   4561549194       0     french
32282748   6277957994       2    spanish
32282749  78110708201       0      czech
32282750  34249770882       2     french
32282751  92101762138       1    italian
32282752  76584861465       2  portugese
32282753  43942131692       1     jewish
32282754  38430091575       1    italian
32282755  34828442497       1     french
32282756  87002969912       1     french
32282757  62546955925       2     jewish
32282758  83541226130       2     french
32282759  65559282025       2     german
32282760  21375072765       1    italian
32282761  90233119766       2      czech
32282762  40806635951       0     jewish
32282763  32600810417       2     muslim
32282764  25486374541       1     french
32282765  60457724733       1      irish
32282766  38329657612       2    spanish
32282767  88166344372       0    spanish
32282768  37354369141       0    spanish
32282769  85661879738       1     french
32282770  22500577701       1     muslim
32282771  67114693751       1     french
32282772  27745744739       1     slavic

[32282773 rows x 3 columns]

In [ ]:
ethn_df['id'] = ethn_df['id'].apply(pd.to_numeric)
ethn_df.dtypes

In [ ]:
ethn_df['ethnicity'].unique()

In [ ]:
dict = {
    'french':'caucasian', 
    'czech':'caucasian', 
    'swedish':'caucasian', 
    'danish':'caucasian', 
    'indian':'southasian', 
    'jewish':'caucasian',
    'russian':'caucasian', 
    'spanish':'hispanic', 
    'irish':'caucasian', 
    'swiss':'caucasian', 
    'muslim':'southasian', 
    'italian':'caucasian',
    'german':'caucasian', 
    'chinese':'eastasian', 
    'japanese':'eastasian', 
    'portugese':'hispanic', 
    'slavic':'caucasian', 
    'greek':'caucasian',
    'korean':'eastasian', 
    'african':'african', 
    'ukranian':'caucasian', 
    'arabic':'southasian', 
    'vietnamese':'eastasian'
}
for i in list(dict):
    ethn_df.replace(i, dict[i], inplace= True)

In [ ]:
ethn_df['ethnicity'].value_counts()

In [ ]:
ethn_df.to_csv("../Data/binned_id_gender_ethnicity.csv")